[package]
name = "imgitor"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
cloud-storage = "0.10"
rocket = "0.5.0-rc.1"
reqwest = "0.11.6"
zip = "0.5.13"
walkdir = "2.3.2"
image = "0.24.0"
regex = "1.5.4"
threadpool = "1.8.1"
unrar = "0.4.4"
webp = "0.2"